; This file was auto-generated by drush make
core = 8.x
api = 2

; Core
; Modules
projects[admin_toolbar][subdir] = "contrib"
projects[admin_toolbar][version] = "1.18"

projects[bg_image_formatter][subdir] = "contrib"
projects[bg_image_formatter][version] = "1.0-beta1"

projects[coffee][subdir] = "contrib"
projects[coffee][version] = "1.0-beta2"

projects[contact_storage][subdir] = "contrib"
projects[contact_storage][version] = "1.0-beta8"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "3.0-alpha27"

projects[devel][subdir] = "contrib"
projects[devel][download][branch] = "1.0-rc1"

projects[entity_reference_revisions][subdir] = "contrib"
projects[entity_reference_revisions][version] = "1.2"

projects[iframe][subdir] = "contrib"
projects[iframe][version] = "1.6"

projects[imce][subdir] = "contrib"
projects[imce][version] = "1.4"

projects[linkit][subdir] = "contrib"
projects[linkit][version] = "4.2"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0"

projects[migrate_plus][subdir] = "contrib"
projects[migrate_plus][version] = "1.0-beta1"

projects[paragraphs][subdir] = "contrib"
projects[paragraphs][version] = "1.0"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.0-rc1"

projects[redirect][subdir] = "contrib"
projects[redirect][download][branch] = "1.0-alpha3"

projects[s3fs][subdir] = "contrib"
projects[s3fs][download][branch] = "2.0-alpha0"

projects[simple_sitemap][subdir] = "contrib"
projects[simple_sitemap][version] = "2.8"

projects[special_menu_items][subdir] = "contrib"
projects[special_menu_items][download][branch] = "1.x-dev"

projects[token][subdir] = "contrib"
projects[token][version] = "1.0-rc1"
